---
title: "STATS 531 - Midterm Project"
output: pdf_document
bibliography: references.bib
format:
  pdf:
    include-in-header:
      text: |
        \RedeclareSectionCommand[
          beforeskip=0.5em,
          runin=false,
          afterskip=0em
        ]{section}
        \RedeclareSectionCommand[
          beforeskip=0em,
          runin=false,
          afterskip=0em
        ]{subsection}
        \RedeclareSectionCommand[
          beforeskip=0em,
          runin=false,
          afterskip=0em
        ]{subsubsection}
        \usepackage{fullpage}
number-sections: true
jupyter: python3
---


We look into the DAX Stock Index in Germany, and investigate how we can model the stock's opening prices, volatility, and other features. The DAX index tracks the performance of the 40 largest companies listed on the Regulated Market of the Frankfurt Stock Exchange [@stoxx_dax_index]. They represent the diversified economy of Germany. The DAX is generally known as the German equity benchmark, surviving for over 30 years. What are the best ways to model changes in the stock's price and its returns? How do we model its volatility, and how accurate are our models? 

# Exploratory Data Analysis
### Introduction 

We look at the daily stock price open for the DAX index for every day from 2010 to 2020 through a time series graph. The data above for stock open shows a roughly nonstationary data. The mean is not constant, and we have a large dip in 2020, likely associated with covid. 

```{python}
#| echo: false
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.legend_handler import HandlerPatch

data = pd.read_csv("data/DAX_2010-2020.csv")

data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y')

data = data.sort_values('Date')

data['Open'] = (
    data['Open']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

data.set_index('Date', inplace=True)

flag_height = 0.1
flag_width = 0.2
# Colors: Black, Red, Gold
colors = ['black', '#DD0000', '#FFCE00']
patches = [mpatches.Rectangle((0, i*flag_height), flag_width, flag_height, 
           color=colors[i]) for i in range(3)]
flag_patch = mpatches.Patch(color='#FFCE00', label='DAX Open Prices')

class HandlerFlag(HandlerPatch):
    def create_artists(self, legend, orig_handle,
                       xdescent, ydescent, width, height, fontsize, trans):
        x = 0
        y = 0
        # Create three rectangles for the flag
        p1 = mpatches.Rectangle((x, y), width, height/3, color='#FFCE00')
        p2 = mpatches.Rectangle((x, y+height/3), width, height/3, color='#DD0000')
        p3 = mpatches.Rectangle((x, y+2*height/3), width, height/3, color='black')
        return [p1, p2, p3]
flag_proxy = mpatches.Patch(color='none', label='DAX Open Prices')

plt.figure(figsize=(10, 2))
plt.plot(data['Open'], label = "DAX Open", color='#006400')
plt.legend(
    handles=[flag_proxy],
    handler_map={flag_proxy: HandlerFlag()}
)
plt.xlabel('Date')
plt.ylabel('Price')
plt.title("DAX 2010-2020 – Open Prices")
plt.show()

```

Now analyze volatility for the DAX stock, calculated as $y_n = log(z_n) - log(z_{n-1})$ [@ionides2026_time_series_intro].

```{python}
#| echo: false
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


data = pd.read_csv("data/DAX_2010-2020.csv")

data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y')

data = data.sort_values('Date')

data['Open'] = (
    data['Open']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

data.set_index('Date', inplace=True)

data['returns'] = np.log(data['Open']) - np.log(data['Open'].shift(1))


flag_height = 0.1
flag_width = 0.2
# Colors: Black, Red, Gold
colors = ['black', '#DD0000', '#FFCE00']
patches = [mpatches.Rectangle((0, i*flag_height), flag_width, flag_height, 
           color=colors[i]) for i in range(3)]
flag_patch = mpatches.Patch(color='#FFCE00', label='DAX Return')

class HandlerFlag(HandlerPatch):
    def create_artists(self, legend, orig_handle,
                       xdescent, ydescent, width, height, fontsize, trans):
        x = 0
        y = 0
        # Create three rectangles for the flag
        p1 = mpatches.Rectangle((x, y), width, height/3, color='#FFCE00')
        p2 = mpatches.Rectangle((x, y+height/3), width, height/3, color='#DD0000')
        p3 = mpatches.Rectangle((x, y+2*height/3), width, height/3, color='black')
        return [p1, p2, p3]
flag_proxy = mpatches.Patch(color='none', label='DAX Return')

plt.figure(figsize=(10, 2))
plt.plot(data['returns'], label = "DAX Returns", color='#006400')
plt.legend(
    handles=[flag_proxy],
    handler_map={flag_proxy: HandlerFlag()}
)
plt.xlabel('Date')
plt.ylabel('Price')
plt.title("DAX 2010-2020 – Returns")
plt.show()
```

Through visual inspection, volatility is stationary with a more or less constant mean. 


### Autocorrelation

 We look at the autocorrelation function below to see how much lags depend on each other. DAX opening prices are all highly correlated from the original value down until the 35th lag. Correlation then drops slowly. This tells us that a model that depends on its lags seems suitable.

```{python}
#| echo: false
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf

data = pd.read_csv("data/DAX_2010-2020.csv")

data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y')
data = data.sort_values('Date')
data['Open'] = (
    data['Open']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)
data.set_index('Date', inplace=True)

fig, ax = plt.subplots(figsize=(8, 2))
plot_acf(data['Open'], ax=ax)
plt.xlabel('Lag t')
plt.ylabel('Autocorrelation $\gamma_{x}(0,t)$')
plt.title('DAX Returns Autocorrelation')
plt.tight_layout()
plt.show()
```

The autocorrelation graph for DAX Returns is below. The correlation of the returns are such that they could be i.i.d.. This means that the relationships between the first price return and its lags aren't as heavily correlated.


```{python}
#| echo: false
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf

data = pd.read_csv("data/DAX_2010-2020.csv")

data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y')
data = data.sort_values('Date')
data['Open'] = (
    data['Open']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)
data.set_index('Date', inplace=True)

data['returns'] = np.log(data['Open']) - np.log(data['Open'].shift(1))

fig, ax = plt.subplots(figsize=(8, 2))
plot_acf(data['returns'].dropna(), ax=ax)
plt.xlabel('Lag t')
plt.ylabel('Autocorrelation $\gamma_{x}(0,t)$')
plt.title('DAX Returns Autocorrelation')
plt.tight_layout()
plt.show()
```

### Distributions

Now we show the histogram for the opening prices, returns, and volatility. These display the shapes of our data. While returns and volatility are normally distributed, opening prices are more uniformally distributed. 

```{python}
#| echo: false
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf

data = pd.read_csv("data/DAX_2010-2020.csv")

data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y')
data = data.sort_values('Date')
data['Open'] = (
    data['Open']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)
data.set_index('Date', inplace=True)

data['returns'] = np.log(data['Open']) - np.log(data['Open'].shift(1))

log_returns = np.log(data['Open'] / data['Open'].shift(1)).dropna()


fig, axes = plt.subplots(1, 3, figsize=(18, 5))  # 1 row, 3 columns

# Histogram 1: Returns
axes[0].hist(data['returns'], bins=50, edgecolor='black', color = '#006400')
axes[0].set_title('Histogram of Returns')
axes[0].set_xlabel(r'DAX Return: $\sigma$ = {:.4f}'.format(data['returns'].std()))
axes[0].set_ylabel('Frequency')

# Histogram 2: Open
axes[1].hist(data['Open'], bins=50, edgecolor='black', color = '#006400')
axes[1].set_title('Histogram of Open')
axes[1].set_xlabel(r'DAX Open: $\sigma$ = {:.4f}'.format(data['Open'].std()))
axes[1].set_ylabel('Frequency')

# Histogram 3: Log Returns (Volatility)
axes[2].hist(log_returns, bins=50, edgecolor='black', color = '#006400')
axes[2].set_title(r'Histogram of $Y_n / Y_{n-1}$')
axes[2].set_xlabel('Y_n / Y_(n-1): $\sigma$ = {:.4f}'.format(np.std(log_returns)))
axes[2].set_ylabel('Frequency')

plt.tight_layout()
plt.show()
```

### Stationary vs Non Stationary

The time series graphs for DAX Opening prices look nonstationary through visual inspection, and the returns for DAX by day look stationary. We obtain empirical data to show whether the data is stationary or not through the Augmented Dickey Fuller Test. A time series model has a unit root if its first difference is stationary. For a linear time series model, this is equivalent to a $(1-B)$ factor in the AR polynomial $\phi(B)$. The Augmented Dickey Fuller Test will look for evidence of a unit root. We use the test to verify the DAX Opening prices are nonstationary, and the returns for the DAX stock index are stationary. 

$$
\begin{aligned}
H_0 &: \text{The process } \{x_t\} \text{ is nonstationary} \\
&\exists\, t, h, k \text{ such that } 
(x_t, x_{t+1}, \dots, x_{t+k}) 
\overset{d}{\neq} 
(x_{t+h}, x_{t+1+h}, \dots, x_{t+k+h}) \\[6pt]
H_A &: \text{The process } \{x_t\} \text{ is stationary} \\
&\forall\, t, h, k,\;
(x_t, x_{t+1}, \dots, x_{t+k})
\overset{d}{=}
(x_{t+h}, x_{t+1+h}, \dots, x_{t+k+h})
\end{aligned}
$$

```{python}
#| echo: false
import pandas as pd
from statsmodels.tsa.stattools import adfuller
from scipy.stats import norm

def adf_summary(series, name):
    result = adfuller(series.dropna())
    
    output = {
        "Series": name,
        "ADF Statistic": result[0],
        "p-value": result[1],
        "Lags Used": result[2],
        "Observations": result[3],
        "Critical Value (5%)": result[4]['5%'],
        "Reject the H0?": "Yes" if result[1] <= 0.05 else "No"
    }
    
    return pd.Series(output)

summary_table = pd.concat([
    adf_summary(data['Open'], "DAX Open"),
    adf_summary(data['returns'], "DAX Returns")
], axis=1)

summary_table
```

Therefore, the DAX Opens has a p value of 0.603955, so, we fail to reject the null, so we may assume it is nonstationary. On the other hand, the DAX Return has a p value of 0 after running the test. We reject the null and there is evidence to show that the data is stationary. 

###  Spectral Density Function 

An estimator of the spectral density function determine a signal’s frequency context content from
a time series sample. It is measured as $\lambda(\omega) = \int_{\infty}^{-\infty} \gamma(x) e^{-2\pi i \omega x}$ [@ionides2026_time_series_intro]. In this section, we look at the frequencies for the DAX Stock Prices and Returns. It splits data into overlapping segments, computes modified periodograms, and averages them to reduce the variance. From the graphs, we may visually inspect the point at which the spectral density is the highest. This will be the dominant frequency, the most common rate at which an oscillation in the stock index happens.

Below, we show frequency vs spectral density function of the DAX Open and Return values.

```{python}
#| echo: false
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.arima_process import ArmaProcess
from statsmodels.tsa.arima.model import ARIMA
from scipy.signal import welch
from scipy.stats import chi2

data = pd.read_csv("data/DAX_2010-2020.csv")

# Clean column names
data.columns = data.columns.str.strip()

data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y')
data = data.sort_values('Date')

data['Open'] = (
    data['Open']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

data.set_index('Date', inplace=True)

nperseg = len(data['Open'])
frequencies, psd = welch(data['Open'].to_numpy(), fs=1, nperseg=nperseg)

idx_max = np.argmax(psd)
dom_freq = frequencies[idx_max]
dom_psd = psd[idx_max]



plt.figure(figsize=(10, 2))
plt.semilogy(frequencies, psd)
plt.axvline(dom_freq, color='red', linestyle='--', 
            label=f'Dominant freq = {dom_freq:.3f}')
plt.scatter(dom_freq, dom_psd, color='red')

plt.xlabel("Frequency")
plt.ylabel("Spectral Density")
plt.title("(Welch) Spectral Density of DAX Open Prices")
plt.show()

```

```{python}
#| echo: false
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.arima_process import ArmaProcess
from statsmodels.tsa.arima.model import ARIMA
from scipy.signal import welch
from scipy.stats import chi2

data = pd.read_csv("data/DAX_2010-2020.csv")

# Clean column names
data.columns = data.columns.str.strip()

data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y')
data = data.sort_values('Date')

data['Open'] = (
    data['Open']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

data.set_index('Date', inplace=True)
data['returns'] = np.log(data['Open']) - np.log(data['Open'].shift(1))
returns = data['returns'].dropna().to_numpy()

nperseg = len(data['returns'])
frequencies, psd = welch(returns, fs=1)

idx_max = np.argmax(psd)
dom_freq = frequencies[idx_max]
dom_psd = psd[idx_max]

plt.figure(figsize=(10, 2))
plt.semilogy(frequencies, psd)
plt.axvline(dom_freq, color='red', linestyle='--', 
            label=f'Dominant freq = {dom_freq:.3f}')
plt.scatter(dom_freq, dom_psd, color='red')
plt.xlabel("Frequency")
plt.ylabel("Spectral Density")
plt.title("(Welch) Spectral Density of DAX Returns")
plt.show()
```

The highest spectral densities in our graphs above are at frequencies of 0.00036 and 0.3, which indicates that these are the dominant frequencies for DAX open and return values, respectively. 

# Fitting Time Series Models

Let's train models on time series data to accurately reflect our observations on the DAX Stock Index from the exploratory data analysis. The DAX Open Prices are nonstationary, while the returns are stationary. 

### ARMA and ARIMA
How do we forecast DAX Stock Prices and Returns? The exploratory data analysis reveals that we can depend on lags and differencing. This information is captured in an ARMA model.

$$ y_n = \phi_1 y_{n-1} + \phi_2 y_{n-2} + \phi_3 y_{n-3} + \theta_1 \epsilon_n + \theta_2 \epsilon_{n-1} $$
$$ y_n = \phi_1 B y_n + \phi_2 B^2 y_n + \phi_3 B^3 y_n + \theta_1 \epsilon_n + \theta_2 B \epsilon_n $$
$$ y_n \phi(B) = \theta(B) \epsilon_n $$



#### DAX Open Prices


Let's analyze the results of an ARIMA model on the DAX Open Prices; our visual analysis and ADF test revealed that the DAX Open Prices as a time series are nonstationary. Because of the COVID wave in 2020, for purposes of fitting a model, we use all results from Januray 1, 2010 to December 31, 2018. The best ARIMA model for DAX Open Prices is an ARIMA(3,1,2). The shape matches, and has a relatively low AIC of -3916.7  - it is trained and graphed on top of raw data below, overlapping almost perfectly.

```{python}
#| echo: false

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("data/DAX_2010-2020.csv")

# Clean column names
data.columns = data.columns.str.strip()

data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y')
data = data.sort_values('Date')

data['Open'] = (
    data['Open']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

data.set_index('Date', inplace=True)
data = data.loc[:'2018-12-31']

# Deal with Warnings
data = data.asfreq('B')
data['Open'] = data['Open'].ffill()

model = ARIMA(data['Open'], order=(3,1,2))
result = model.fit()

# In-sample prediction (in original scale)
pred = result.predict(start=data.index[0], end=data.index[-1], typ='levels')

plt.figure(figsize=(10,2))
plt.plot(data.index, data['Open'], label='Actual Open', color='yellow')
plt.plot(data.index, pred, label='ARIMA Predicted', color='blue')
plt.title("DAX Open vs ARIMA(3,1,2) Prediction")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.show()
```


The AIC values for the ARIMA models of different number of parameters (ex, ARIMA(1,0,1), ARIMA(2,0,2), etc.) are in the tables below.

\begin{table}[ht]
\centering
\caption{AIC for ARIMA(p,d,q) Model Comparison}
\label{tab:arma_all}

\begin{subtable}{0.32\textwidth}
\centering
\small
\resizebox{\linewidth}{!}{
\begin{tabular}{lccccc}
\toprule
 & \multicolumn{5}{c}{MA Order} \\
\cmidrule(lr){2-6}
AR Order & 0 & 1 & 2 & 3 & 4 \\
\midrule
0 & 10629.7 & 7529.3 & 5005.4 & 3147.4 & 1892.3 \\
1 & -3897.5 & -3895.6 & -3893.6 & -3893.5 & -3892.2 \\
2 & -3895.6 & -3894.0 & -3892.1 & -3891.9 & -3891.6 \\
3 & -3893.6 & -3892.4 & -3891.1 & -3898.6 & -3896.7 \\
4 & -3893.6 & -3891.3 &  -3889.2 & -3896.6 & -3895.1 \\
\bottomrule
\end{tabular}
}
\caption{AIC for $d = 0$}
\end{subtable}
\hfill
\begin{subtable}{0.32\textwidth}
\centering
\small
\resizebox{\linewidth}{!}{
\begin{tabular}{lccccc}
\toprule
 & \multicolumn{5}{c}{MA Order} \\
\cmidrule(lr){2-6}
AR Order & 0 & 1 & 2 & 3 & 4 \\
\midrule
0 & -3905.2 & -3903.3 & -3901.3 & -3901.2 & -3899.9 \\
1 & -3903.3 & -3901.3 & -3899.3 & -3899.3 & -3901.8 \\
2 & -3901.3 & -3899.8 & -3916.6 & -3906 & -3903.5 \\
3 & -3901.3 & -3899.3 & -3916.7 & -3904.1 & -3903.7 \\
4 & -3899.8 & -3901.5 & -3903.9 & -3902.4 & -3915.5 \\
\bottomrule
\end{tabular}
}
\caption{AIC for $d = 1$}
\end{subtable}
\hfill
\begin{subtable}{0.32\textwidth}
\centering
\small
\resizebox{\linewidth}{!}{
\begin{tabular}{lccccc}
\toprule
 & \multicolumn{5}{c}{MA Order} \\
\cmidrule(lr){2-6}
AR Order & 0 & 1 & 2 & 3 & 4 \\
\midrule
0 & -2267.9 & -3893.6 & -3891.6 & -3889.7 & -3889.5 \\
1 & -2939.6 & -3891.6 & -3889.6 & -3887.7 & -3885.7 \\
2 & -3253.7 & -3889.7 & -3887.6 & -3887.4 & -3904.9 \\
3 & -3378.4 & -3889.6 & -3885.7 & -3885.2 & -3888.2 \\
4 & -3432 & -3888.1 & -3885.7 & -3883.3 & -3898.7 \\
\bottomrule
\end{tabular}
}
\caption{AIC for $d = 2$}
\end{subtable}
\hfill
\end{table}


#####  Model Diagnosis
We check causality and invertibility in this section. Causality is when the AR process has all roots that lie outside the unit circle. Invertability is when the MA process has all roots that lie outside the unit circle. We diagnose our best solution, ARIMA (3,1,2) below.

```{python}
#| echo: false
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("data/DAX_2010-2020.csv")

# Clean column names
data.columns = data.columns.str.strip()

data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y')
data = data.sort_values('Date')

data['Open'] = (
    data['Open']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

data.set_index('Date', inplace=True)
data = data.loc[:'2018-12-31']

# Deal with Warnings
data = data.asfreq('B')
data['Open'] = data['Open'].ffill()

model = ARIMA(data['Open'], order=(3,1,2))
result = model.fit()

ar_roots = result.arroots
# print("AR roots:", ar_roots)

# MA roots
ma_roots = result.maroots
# print("MA roots:", ma_roots)

# We remove outliers in the AR solutions so that our visualization does not suffer.
ar_roots_plot = ar_roots[np.abs(ar_roots) < 10]

def plot_roots_ax(ax, roots, title):
    theta = np.linspace(0, 2*np.pi, 100)
    x = np.cos(theta)
    y = np.sin(theta)
    
    ax.plot(x, y, 'k--', label='Unit Circle')  # unit circle
    ax.scatter(roots.real, roots.imag, color='red', s=100, label='Roots')
    ax.axhline(0, color='grey', lw=1)
    ax.axvline(0, color='grey', lw=1)
    ax.set_xlabel('Real')
    ax.set_ylabel('Imag')
    ax.set_title(title)
    ax.grid(True)
    ax.set_aspect('equal', adjustable='datalim')
    # ax.set_xlim(-1.5, 1.5)  # zoom to unit circle
    # ax.set_ylim(-1.5, 1.5)
    ax.legend()

# Create side-by-side plots
fig, axs = plt.subplots(1, 2, figsize=(10,2))

plot_roots_ax(axs[0], ar_roots_plot, 'AR Roots (Zoomed)')
plot_roots_ax(axs[1], ma_roots, 'MA Roots')

plt.tight_layout()
plt.show()

```
We therefore see that all roots lie outside the unit circle. Therefore, our solution is both causal and invertible. 


##### Residual Analysis
Now we look at the residuals. 

```{python}
#| echo: false
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

data = pd.read_csv("data/DAX_2010-2020.csv")

# Clean column names
data.columns = data.columns.str.strip()

data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y')
data = data.sort_values('Date')

data['Open'] = (
    data['Open']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

data.set_index('Date', inplace=True)
data = data.loc[:'2018-12-31']

# Deal with Warnings
data = data.asfreq('B')
data['Open'] = data['Open'].ffill()

model = ARIMA(data['Open'], order=(3,1,2))
result = model.fit()

# Get residuals
residuals = result.resid

fig, axs = plt.subplots(1, 2, figsize=(10,3))

# Histogram
axs[0].hist(residuals, bins=30, edgecolor='k')
axs[0].set_title('Histogram of Residuals')
axs[0].set_xlabel('Residual')
axs[0].set_ylabel('Frequency')

# QQ plot
sm.qqplot(residuals, line='45', ax=axs[1])
axs[1].set_title('QQ Plot of Residuals')

plt.tight_layout()
plt.show()

```

#### DAX Returns
Let's run the same procedure for the returns. The best model is ARIMA(3, 0, 4)


```{python}
#| echo: false
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("data/DAX_2010-2020.csv")

# Clean column names
data.columns = data.columns.str.strip()

data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y')
data = data.sort_values('Date')

data['Open'] = (
    data['Open']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

data.set_index('Date', inplace=True)
data = data.loc[:'2018-12-31']

# Deal with Warnings
data = data.asfreq('B')
data['Open'] = data['Open'].ffill()
data['returns'] = np.log(data['Open']) - np.log(data['Open'].shift(1))

returns = data['returns'].dropna()

model = ARIMA(returns, order=(3,0,4))
result = model.fit()

# In-sample prediction
pred = result.predict(start=0, end=len(returns)-1, typ='levels')

plt.figure(figsize=(10,2))
plt.plot(returns.index, returns, label='Returns', color='yellow')
plt.plot(returns.index, pred, label='ARIMA Predicted', color='blue')
plt.title("DAX Open vs ARIMA(3,0,4) Prediction")
plt.xlabel("Date")
plt.ylabel("Returns")
plt.legend()
plt.show()

```

Now, we look at AIC for every combination of parameters in ARIMA(p,d,q) for DAX returns.

\begin{table}[ht]
\centering
\caption{AIC for ARIMA(p,d,q) Model Comparison}
\label{tab:arma_all}

\begin{subtable}{0.32\textwidth}
\centering
\small
\resizebox{\linewidth}{!}{
\begin{tabular}{lccccc}
\toprule
 & \multicolumn{5}{c}{MA Order} \\
\cmidrule(lr){2-6}
AR Order & 0 & 1 & 2 & 3 & 4 \\
\midrule
0 & 10629.7 & 7529.3 & 5005.4 & 3147.4 & 1892.3 \\
1 & -3897.5 & -3895.6 & -3893.6 & -3893.5 & -3892.2 \\
2 & -3895.6 & -3894 & -3892 & -3891.9 & -3891.6 \\
3 & -3893.6 & -3892.4 & -3891.1 &  -3898.6 & -3896.7 \\
4 & -3893.6 & -3891.3 & -3889.2 & -3896.6 & -3895.1 \\
\bottomrule
\end{tabular}
}
\caption{AIC for $d = 0$}
\end{subtable}
\hfill
\begin{subtable}{0.32\textwidth}
\centering
\small
\resizebox{\linewidth}{!}{
\begin{tabular}{lccccc}
\toprule
 & \multicolumn{5}{c}{MA Order} \\
\cmidrule(lr){2-6}
AR Order & 0 & 1 & 2 & 3 & 4 \\
\midrule
0 & -3905.2 & -3903.3 & -3901.3 & -3901.2 & -3899.9 \\
1 & -3903.3 & -3901.3 & -3899.3 & -3899.3 & -3901.8 \\
2 & -3901.3 & -3899.8 & -3916.6 & -3906 & -3903.5 \\
3 & -3901.2 & -3899.2 & -3916.7 & -3904.0 & -3903.7 \\
4 & -3899.8 & -3901.5 & -3903.9 & -3902.4 & -3915.5 \\
\bottomrule
\end{tabular}
}
\caption{AIC for $d = 1$}
\end{subtable}
\hfill
\begin{subtable}{0.32\textwidth}
\centering
\small
\resizebox{\linewidth}{!}{
\begin{tabular}{lccccc}
\toprule
 & \multicolumn{5}{c}{MA Order} \\
\cmidrule(lr){2-6}
AR Order & 0 & 1 & 2 & 3 & 4 \\
\midrule
0 & -2267.9 & -3893.6 & -3891.6& -3889.7 & -3889.5\\
1 & -2939.6 & -3891.6 & -3889.6 & -3887.7 & -3885.7 \\
2 & -3253.7 & -3889.7 & -3887.6 & -3887.4 & -3904.9 \\
3 & -3378.4 & -3889.6 & -3885.7 &  -3885.2 & -3888.2 \\
4 & -3432 & -3888.1 & -3885.7 & -3883.3 & -3898.7 \\
\bottomrule
\end{tabular}
}
\caption{AIC for $d = 2$}
\end{subtable}
\hfill
\end{table}







##### Model Diagnosis
Now we assess causality and invertability.

```{python}
#| echo: false
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("data/DAX_2010-2020.csv")

# Clean column names
data.columns = data.columns.str.strip()

data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y')
data = data.sort_values('Date')

data['Open'] = (
    data['Open']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

data.set_index('Date', inplace=True)
data = data.loc[:'2018-12-31']

# Deal with Warnings
data = data.asfreq('B')
data['Open'] = data['Open'].ffill()

data['returns'] = np.log(data['Open']) - np.log(data['Open'].shift(1))

returns = data['returns'].dropna()


model = ARIMA(returns, order=(3,0,4))
result = model.fit()

ar_roots = result.arroots
# print("AR roots:", ar_roots)

# MA roots
ma_roots = result.maroots
# print("MA roots:", ma_roots)

# We remove outliers in the AR solutions so that our visualization does not suffer.
ar_roots_plot = ar_roots[np.abs(ar_roots) < 10]

def plot_roots_ax(ax, roots, title):
    theta = np.linspace(0, 2*np.pi, 100)
    x = np.cos(theta)
    y = np.sin(theta)
    
    ax.plot(x, y, 'k--', label='Unit Circle')  # unit circle
    ax.scatter(roots.real, roots.imag, color='red', s=100, label='Roots')
    ax.axhline(0, color='grey', lw=1)
    ax.axvline(0, color='grey', lw=1)
    ax.set_xlabel('Real')
    ax.set_ylabel('Imag')
    ax.set_title(title)
    ax.grid(True)
    ax.set_aspect('equal', adjustable='datalim')
    # ax.set_xlim(-1.5, 1.5)  # zoom to unit circle
    # ax.set_ylim(-1.5, 1.5)
    ax.legend()

# Create side-by-side plots
fig, axs = plt.subplots(1, 2, figsize=(10,2))

plot_roots_ax(axs[0], ar_roots_plot, 'AR Roots (Zoomed)')
plot_roots_ax(axs[1], ma_roots, 'MA Roots')

plt.tight_layout()
plt.show()

```

All solutions lie outside the unit circle. Therefore, they are all causal and invertible. 

##### Residuals
Now we look at the residuals.

```{python}
#| echo: false
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("data/DAX_2010-2020.csv")

# Clean column names
data.columns = data.columns.str.strip()

data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y')
data = data.sort_values('Date')

data['Open'] = (
    data['Open']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

data.set_index('Date', inplace=True)
data = data.loc[:'2018-12-31']

# Deal with Warnings
data = data.asfreq('B')
data['Open'] = data['Open'].ffill()

data['returns'] = np.log(data['Open']) - np.log(data['Open'].shift(1))

returns = data['returns'].dropna()


model = ARIMA(returns, order=(3,0,4))
result = model.fit()

# Get residuals
residuals = result.resid

fig, axs = plt.subplots(1, 2, figsize=(10,2))

# Histogram
axs[0].hist(residuals, bins=30, edgecolor='k')
axs[0].set_title('Histogram of Residuals')
axs[0].set_xlabel('Residual')
axs[0].set_ylabel('Frequency')

# QQ plot
sm.qqplot(residuals, line='45', ax=axs[1])
axs[1].set_title('QQ Plot of Residuals')

plt.tight_layout()
plt.show()

```


### SARMA and SARIMA
The Seasonal Autoregressive Moving Average Model (SARMA) adds a seasonal component to the ARMA and ARIMA Models. Instead of considering every lag from 1 to 35, for example, we can take lags 1, 12, and 13, repeatedly. This allows for monthly and yearly coefficients in our model, as one would expect with stock. We show a representation of SARIMAX(2,0,2)(1,0,0,12), and how well it performs below.

$$ By_n = y_{n-1}; B^2 y_n = y_{n-2}; B^{12} y_n = y_{n-12}  $$
$$ y_t - \phi_1 y_{t-1} - \phi_2 y_{t-2} - \Phi_1 y_{t-12} + \Phi_1 \phi_1 y_{t-13} + \Phi_1 \phi_2 y_{t-14} = \epsilon_t + \theta_1 \epsilon_{t-1} + \theta_2 \epsilon_{t-2} $$
$$ (1 - \Phi_1 B^{12}) (1 - \phi_1 B - \phi_2 B^2) \, y_t = (1 + \theta_1 B + \theta_2 B^2) \, \epsilon_t $$
$$ \Phi(B^{12}) \, \phi(B) \, y_t = \theta(B) \, \Theta(B^{12}) \, \epsilon_t$$


```{python}
#| echo: false

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.statespace.sarimax import SARIMAX

# TODO: look into warning

import warnings
from statsmodels.tools.sm_exceptions import ConvergenceWarning

# Suppress all warnings (careful!)
warnings.filterwarnings("ignore")

# Or suppress just SARIMAX starting parameter warnings
warnings.filterwarnings("ignore", message="Non-stationary starting seasonal autoregressive")

data = pd.read_csv("data/DAX_2010-2020.csv")

data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y')
data = data.sort_values('Date')

data['Open'] = (
    data['Open']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

data.set_index('Date', inplace=True)
data = data.loc[:'2018-12-31']
data = data.asfreq('B')  # Business day frequency
data['Open'] = data['Open'].ffill()


# Returns Model
data['returns'] = np.log(data['Open']) - np.log(data['Open'].shift(1))
returns = data['returns'].dropna()
model_returns = SARIMAX(data['Open'],order=(2, 0, 2), trend='c', seasonal_order=(1, 0, 0, 12), enforce_stationarity=True)
results_returns = model.fit()
sim_returns = result.simulate(nsimulations=len(returns))

# Open Model
model_open = SARIMAX(data['Open'],
                     order=(2, 0, 2),
                     seasonal_order=(1, 0, 0, 12),
                     trend='c',
                     enforce_stationarity=True)
results_open = model_open.fit()
sim_open = results_open.simulate(nsimulations=len(data))

fig, axs = plt.subplots(1, 2, figsize=(10, 2))

# Open prices vs SARIMA
axs[0].plot(data.index, data['Open'], label='Open', color='blue')
axs[0].plot(data.index, sim_open, label='SARIMA Open', color='red')
axs[0].set_title('Open Prices vs SARIMA Simulation')
axs[0].legend()

# Returns vs SARIMA
axs[1].plot(returns.index, returns, label='Returns', color='yellow')
axs[1].plot(returns.index, sim_returns, label='SARIMA Returns', color='green')
axs[1].set_title('Log Returns vs SARIMA Simulation')
axs[1].legend()

plt.tight_layout()
plt.show()
```

The SARIMA models for DAX Open prices and returns have AIC values of -3897.623886161021 and -14029.486910232028.



### GARCH
We fit a GARCH model. The GARCH(1, 1) models the following:

$$
\begin{aligned}
r_t &= \mu_t + \varepsilon_t \\
\varepsilon_t &= \sigma_t e_t \\
\sigma_t^2 & = \omega + \alpha \varepsilon_{t-1}^2 + \beta \sigma_{t-1}^2,
\end{aligned}
$$
where $r_t$ are the returns, $\mu_t$ is the mean function, $\varepsilon_t$ is the residual at time $t$, and $e_t$ is some iid noise distribution which we assume here is scaled to have variance 1 (say, $e_t \sim N(0, 1)$ for simplicity). Thus, if we denote $\mathcal{F}_{t-1}$ as the $\sigma$-algebra (intuitively, information) generated by $\varepsilon_t, \sigma_{t-1}^2$ then we have 
$$
\begin{aligned}
Var(r_t - \mu_t \mid \mathcal{F}_{t-1}) = Var(\varepsilon_t \mid \mathcal{F}_{t-1}) & = Var(\sigma_t e_t \mid \mathcal{F}_{t-1}) \\
& = \sigma^2_t Var(e_t \mid \mathcal{F}_{t-1}) \qquad (\sigma_t \text{ is } \mathcal{F}_{t-1} \text{ measurable}) \\
& = \sigma^2_t Var(e_t) \qquad (e_t \text{ is independent of } \mathcal{F}_{t-1}) \\
& = \sigma^2_t.
\end{aligned}
$$

We see that GARCH models essentially fit an ARMA model to $\sigma^2_t$ where the moving average terms are the squared residuals of the returns series.

Now, for simplicity, assume that $\mu_t = 0$ for all $t$. Indeed, for our log returns data, this seems appropriate, given that $ARMA(0, 0)$ was favorable via AIC, there was constant trend visible in the plot, and since $\bar{x} \approx 0.02$ for our data. Then we have
$$
E(r_t^2 \mid \mathcal{F}_{t-1}) = Var(r_t \mid \mathcal{F}_{t-1}) = \sigma_t^2,
$$
and hence
$$
E(r_t^2) = E(E(r_t^2 \mid \mathcal{F}_{t-1})) = E(\sigma_t^2),
$$
Thus, $r_t^2$ is a conditionally unbiased estimator for $\sigma_t^2$ (and the two are equal in marginal expectation). Thus, for simplicity, it is theoretically favorable to use $r_t^2$ as a realized volatility proxy for comparison. The disadvantage is that although it is conditionally unbiased, it is high variance. 
```{python}
#| echo: false
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.statespace.sarimax import SARIMAX
import numpy as np
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.tsa.stattools import acf
from statsmodels.stats.diagnostic import acorr_ljungbox
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error
from arch import arch_model

def aic_table(data, P, Q, d=0, model_type='sarimax', dist='normal'):
    table = np.zeros((P+1, Q+1))
    model_type = model_type.strip().lower()
    for p in range(P+1):
        for q in range(Q+1):
            try:
                if model_type == 'sarimax':
                    model = SARIMAX(data,
                                    trend = 'c',
                                    order=(p, d, q))
                elif model_type == 'garch':
                    # if p == 0:
                    #     continue # NaNs only for ARCH(0)
                    model = arch_model(data,
                                       vol='GARCH',
                                       p=p,
                                       q=q,
                                       dist=dist)
                else:
                    raise ValueError
                results = model.fit()
                table[p, q] = results.aic # sarimax, garch have aic attribute
            except:
                table[p, q] = np.nan
    if model_type == 'sarimax':
        df = pd.DataFrame(table,
            index=[f'AR{p}' for p in range(P+1)],
            columns=[f'MA{q}' for q in range(Q+1)])
    elif model_type == 'garch':
        df = pd.DataFrame(table,
            index=[f'ARCH{p}' for p in range(P+1)], # by this, I mean there are is dependence on the p previous epsilon values
            columns=[f'GARCH{q}' for q in range(Q+1)]) # by this, I mean there are q "GARCH" terms in that there is dependence on the q previous sigma^2 values
    else:
        raise ValueError
    return df



data = pd.read_csv("data/DAX_2010-2020.csv")
data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y')
data = data.sort_values('Date')
data = data[data['Date'] < '2020-01-01']


data.set_index('Date', inplace=True)
data = data.asfreq('B')  # Business day frequency
data['Open'] = data['Open'].ffill()

df = data.copy()
df = df[['Open']]
df = df[df.index < '2019-01-01']
df["Open"] = df["Open"].str.replace(",", "", regex=False).astype(float) # remove undesirable comma formatting in the price

df2 = df.copy()
df2 = np.log(df['Open'])
df2 = df2.diff().dropna()
df2 = df2 * 100



# aic_table(df2, P = 4, Q = 4, model_type='garch')


model_g11 = arch_model(df2,
                        vol='GARCH',
                        p=1,
                        q=1).fit(disp="off")
# print(model_g11.summary())

estimated_vol = model_g11.conditional_volatility

# credit to https://blog.quantinsti.com/garch-gjr-garch-volatility-forecasting-python/ for this suggestion
realized_vol = df2.rolling(window=5).std()  # 5-day window for smoothing. Includes data from time t

# comparing GARCH conditional volatility estimate to r_t^2 as this seems to be more common in literature?
# for example, see https://link.springer.com/chapter/10.1007/978-3-030-46347-2_8
realized_vol_v2 = df2**2


plt.figure(figsize=(10, 2))

plt.plot(df2.index, realized_vol, label='Realized Volatility (Smoothed Estimate)')
plt.plot(df2.index, estimated_vol, label='Model Estimated Volatility')

plt.xlabel('Date')
plt.ylabel('Volatility')
plt.title('Realized vs Estimated Volatility')
plt.legend()

plt.show()

plt.figure(figsize=(10, 2))

plt.plot(df2.index, realized_vol_v2, label='Realized Volatility (Squared log returns)')
plt.plot(df2.index, estimated_vol**2, label='Model Estimated Volatility')

plt.xlabel('Date')
plt.ylabel('Volatility')
plt.title('Realized vs Estimated Volatility')
plt.legend()

plt.show()

```


# References 